# from rest_framework import routers
from django.urls import path, include
from . import views

# router = routers.DefaultRouter()
# router.register()

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='api-login'),
    path('logout/', views.UserLogoutView.as_view(), name='api-logout'),
    path('profile/', views.UserProfileView.as_view(), name='api-profile'),
    path('tailors/', views.TailorListView.as_view(), name='api-tailors'),
    path('female-services/', views.FemaleServiceListView.as_view(), name='api-female-services'),
    path('male-services/', views.MaleServiceListView.as_view(), name='api-male-services'),
    path('orders/', views.OrderListView.as_view(), name='api-orders'),
    path('order-detail/<int:id>/', views.OrderDetailView.as_view(), name='api-order-detail'),
    path('measurement/', views.CustomerMeasurementView.as_view(), name='api-measurement'),
    path('customer-select-service/', views.CustomerSelectServiceView.as_view(), name='api-customer-select-service'),
    path('customer-selected-service/', views.CustomerSelectedServiceView.as_view(), name='api-customer-selected-service'),
    path('customer-delete-selected-service/<int:id>/', views.CustomerDeleteSelectedServiceView.as_view(), name='api-customer-delete-selected-service'),
    path('customer-service-detail/<int:id>/', views.CustomerServiceDetailView.as_view(), name='api-customer-service-detail'),
    path('customer-place-order-preview/', views.CustomerPlaceOrderPreviewView.as_view(), name='api-customer-place-order-preview'),
    path('customer-place-order/', views.CustomerPlaceOrderView.as_view(), name='api-customer-place-order'),
    path('customer-cancel-order/<int:id>/', views.CustomerCancelOrderView.as_view(), name='api-customer-cancel-order'),
    path('tailor-upcoming-orders/', views.TailorUpcomingOrderView.as_view(), name='api-tailor-upcoming-orders'),
    path('tailor-accept-order/<int:id>/', views.TailorAcceptOrderView.as_view(), name='api-tailor-accept-order'),
    path('tailor-reject-order/<int:id>/', views.TailorRejectOrderView.as_view(), name='api-tailor-reject-order'),
    path('tailor-complete-order/<int:id>/', views.TailorCompleteOrderView.as_view(), name='api-complete-order'),
    path('tailor-accepted-orders/', views.TailorAcceptedOrdersView.as_view(), name='api-tailor-accepted-orders'),
    path('tailor-earnings/', views.TailorEaringsView.as_view(), name='api-tailor-earnings'),
    path('tailor-request-earning/<int:id>/', views.TailorEaringRequestView.as_view(), name='api-tailor-request-earning'),
    path("delivery-boy-upcoming-order/",views.DeliveryBoyUpcomingOrder.as_view(),name='api-delivery-boy-upcoming-order'),
    path("tailor-complete-order-list/",views.TailorCompleteOrderViewList.as_view(),name='api-tailor-complete-order-list'),
    path('delivery-boy-accept-order/<int:id>/',views.DeliveryBoyAcceptOrder.as_view(),name='api-delivery-boy-accept-order'),
    path('delivery-boy-reject-order/<int:id>/',views.DeliveryBoyRejectOrder.as_view(),name='api-delivery-boy-reject-order'),
    path('delivery-boy-accepted-order-list/',views.DeliveryBoyAccptedOrderList.as_view(), name='api-delivery-boy-accepted-order-list'),
    path('delivery-boy-picked-for-sevice/<int:id>/',views.DeliveryBoyPickedForService.as_view(), name='api-delivery-boy-picked-for-sevice'),
    path('delivery-boy-delivered-sevice/<int:id>/',views.DeliveryBoyDeliveredService.as_view(), name='delivery-boy-delivered-sevice'),
    path('delivery-boy-complete-delivered-list/',views.DeliveryBoyCompeleteDeliveryList.as_view(), name='api-delivery-boy-complete-delivered-list'),
    path('receive-notification-list/',views.ReceiveNotification.as_view(), name='api-receive-notification-list'),
    path('delivery-boy-total-earning/',views.DeliveryBoyTotalEarning.as_view(), name='api-delivery-boy-total-earning'),
    path('near-by-tailor-list/',views.NearByTailors.as_view(), name='api-near-by-tailor-list'),
    path('tailor-toatal-earning/',views.Tailor_Earning.as_view(), name='api-tailor-toatal-earning'),
    path('customer-delete-selected-services/',views.CustomerSelectServicedeleted.as_view(), name='api-customer-delete-selected-services'),
    path('delete-single-notification/<int:id>/',views.DeleteSingleNotification.as_view(), name='api-delete-single-notification'),
    path('delete-all-notification/',views.DeleteAllNotification.as_view(), name='api-delete-all-notification'),
    path('notification-count/',views.NotificationCount.as_view(), name='api-notification-count'),
    path('tailor-measurement-show/<int:id>/',views.TailorShowMeasurement.as_view(), name='api-tailor-measurement-show'),
    path('tailor-get-measurement/',views.Tailor_get_measurement.as_view(), name='api-tailor-get-measurement'),
    path('terms-and-conditions/',views.TermandCondition.as_view(), name='api-terms-and-conditions'),
    path('privacy-and-policy/',views.PrivacyandPolicy.as_view(), name='api-privacy-and-policy'),
    path('tailor-earning-request/',views.TailorEaringRequestView.as_view(), name='api-tailor-earning-request'),
    path('earning-withdrow-list/',views.EarningWithdrowlist.as_view(), name='api-earning-withdrow-list'),
    path('delivery-boy-earning-request/',views.DeliveryBoyRequestEarning.as_view(), name='api-delivery-boy-earning-request'),
]